spring.application.name=01AdharManagement
# Global Application Settings


# Default Active Profile (Change this to switch environments locally)
#spring.profiles.active=prod

# Server Configuration
server.port=8080

# Common JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true