spring.application.name=01AdharManagement
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl
spring.datasource.username=system
spring.datasource.password=tiger
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialect for modern Oracle versions (Oracle 12c, 19c, 21c, etc.)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
